# Generated by Django 5.2.3 on 2025-06-12 13:37

import ckeditor.fields
import django.db.models.deletion
import main.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('title_ru', models.CharField(max_length=300, null=True)),
                ('title_uz', models.CharField(max_length=300, null=True)),
                ('text', models.TextField()),
                ('text_ru', models.TextField(null=True)),
                ('text_uz', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('name_ru', models.CharField(max_length=300, null=True)),
                ('name_uz', models.CharField(max_length=300, null=True)),
                ('image', models.ImageField(upload_to=main.utils.generate_unique_filename)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=main.utils.generate_unique_filename)),
            ],
        ),
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('name_ru', models.CharField(max_length=300, null=True)),
                ('name_uz', models.CharField(max_length=300, null=True)),
                ('image', models.ImageField(upload_to=main.utils.generate_unique_filename)),
                ('description', models.TextField()),
                ('description_ru', models.TextField(null=True)),
                ('description_uz', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('name_ru', models.CharField(max_length=300, null=True)),
                ('name_uz', models.CharField(max_length=300, null=True)),
                ('image', models.ImageField(upload_to=main.utils.generate_unique_filename)),
                ('address', models.CharField(max_length=300)),
                ('address_ru', models.CharField(max_length=300, null=True)),
                ('address_uz', models.CharField(max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('title_ru', models.CharField(max_length=300, null=True)),
                ('title_uz', models.CharField(max_length=300, null=True)),
                ('video', models.FileField(upload_to=main.utils.generate_unique_filename)),
                ('year_of_traditions', models.IntegerField()),
                ('countries', models.IntegerField()),
                ('projects', models.IntegerField()),
                ('clients', models.IntegerField()),
                ('facebook_link', models.CharField(max_length=300)),
                ('telegram_link', models.CharField(max_length=300)),
                ('youtube_link', models.CharField(max_length=300)),
                ('whatsapp_link', models.CharField(max_length=300)),
                ('instagram_link', models.CharField(max_length=300)),
                ('email', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('name_ru', models.CharField(max_length=300, null=True)),
                ('name_uz', models.CharField(max_length=300, null=True)),
                ('youtube_link', models.CharField(max_length=300)),
                ('model', models.CharField(max_length=300)),
                ('model_ru', models.CharField(max_length=300, null=True)),
                ('model_uz', models.CharField(max_length=300, null=True)),
                ('appointment', models.CharField(max_length=300)),
                ('appointment_ru', models.CharField(max_length=300, null=True)),
                ('appointment_uz', models.CharField(max_length=300, null=True)),
                ('permissible_load', models.CharField(max_length=300)),
                ('permissible_load_ru', models.CharField(max_length=300, null=True)),
                ('permissible_load_uz', models.CharField(max_length=300, null=True)),
                ('construction', models.CharField(max_length=300)),
                ('construction_ru', models.CharField(max_length=300, null=True)),
                ('construction_uz', models.CharField(max_length=300, null=True)),
                ('guarantee', models.CharField(max_length=300)),
                ('guarantee_ru', models.CharField(max_length=300, null=True)),
                ('guarantee_uz', models.CharField(max_length=300, null=True)),
                ('country', models.CharField(max_length=300)),
                ('country_ru', models.CharField(max_length=300, null=True)),
                ('country_uz', models.CharField(max_length=300, null=True)),
                ('description', ckeditor.fields.RichTextField()),
                ('description_ru', ckeditor.fields.RichTextField(null=True)),
                ('description_uz', ckeditor.fields.RichTextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('name_ru', models.CharField(max_length=300, null=True)),
                ('name_uz', models.CharField(max_length=300, null=True)),
                ('image', models.ImageField(upload_to=main.utils.generate_unique_filename)),
                ('description', models.TextField()),
                ('description_ru', models.TextField(null=True)),
                ('description_uz', models.TextField(null=True)),
                ('address', models.TextField()),
                ('address_ru', models.TextField(null=True)),
                ('address_uz', models.TextField(null=True)),
                ('country', models.CharField(max_length=300)),
                ('country_ru', models.CharField(max_length=300, null=True)),
                ('country_uz', models.CharField(max_length=300, null=True)),
                ('link', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Why',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('name_ru', models.CharField(max_length=300, null=True)),
                ('name_uz', models.CharField(max_length=300, null=True)),
                ('image', models.ImageField(upload_to=main.utils.generate_unique_filename)),
                ('description', models.TextField()),
                ('description_ru', models.TextField(null=True)),
                ('description_uz', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=main.utils.generate_unique_filename)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.product')),
            ],
        ),
    ]
