# Generated by Django 5.2.3 on 2025-06-12 13:57

import main.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='why',
            name='image',
            field=models.FileField(upload_to=main.utils.generate_unique_filename),
        ),
    ]
