# Generated by Django 5.2.3 on 2025-06-12 14:04

import main.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_why_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='image',
            field=models.FileField(upload_to=main.utils.generate_unique_filename),
        ),
    ]
