# Generated by Django 5.2.3 on 2025-06-15 07:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_feature_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='appointment',
        ),
        migrations.RemoveField(
            model_name='product',
            name='appointment_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='appointment_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='construction',
        ),
        migrations.RemoveField(
            model_name='product',
            name='construction_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='construction_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='country',
        ),
        migrations.RemoveField(
            model_name='product',
            name='country_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='country_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='guarantee',
        ),
        migrations.RemoveField(
            model_name='product',
            name='guarantee_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='guarantee_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='model',
        ),
        migrations.RemoveField(
            model_name='product',
            name='model_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='model_uz',
        ),
        migrations.RemoveField(
            model_name='product',
            name='permissible_load',
        ),
        migrations.RemoveField(
            model_name='product',
            name='permissible_load_ru',
        ),
        migrations.RemoveField(
            model_name='product',
            name='permissible_load_uz',
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=300)),
                ('key_ru', models.CharField(max_length=300, null=True)),
                ('key_uz', models.CharField(max_length=300, null=True)),
                ('value', models.CharField(max_length=300)),
                ('value_ru', models.CharField(max_length=300, null=True)),
                ('value_uz', models.CharField(max_length=300, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='main.product')),
            ],
        ),
    ]
